[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['cd backend && composer install --optimize-autoloader --no-dev --no-interaction']

[phases.build]
cmds = ['cd backend && mkdir -p storage/framework/{sessions,views,cache} storage/logs bootstrap/cache && chmod -R 775 storage bootstrap/cache']

[start]
cmd = 'cd backend && php artisan migrate:fresh --force && php artisan serve --host=0.0.0.0 --port=$PORT'
